name: Auto Update Full Site

on:
  schedule:
    - cron: '*/30 * * * *'  # каждые 30 минут
  workflow_dispatch:        # возможность запускать вручную

jobs:
  update-site:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: pip install --upgrade pip

    - name: Run update_stats.py (если есть)
      run: python update_stats.py

    # Если у тебя есть сборка сайта — раскомментируй и подставь команду
    # - name: Build site
    #   run: python build.py

    - name: Commit and push changes
      run: |
        git config --global user.email "github-actions@github.com"
        git config --global user.name "GitHub Actions"
        git add .
        git commit -m "🔄 Auto update full site" || echo "No changes to commit"
        git push